version: "3.3"
services:
        leafylink:
                image: "${COMPOSE_PROJECT_NAME}"
                volumes:
                        - "/etc/timezone:/etc/timezone:ro"
                        - "/etc/localtime:/etc/localtime:ro"
                ports:
                        - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
                build: .
                container_name: "${COMPOSE_PROJECT_NAME}"
